# Generated by Django 2.2.5 on 2021-06-27 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomCategory', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DimentionDeQulite',
            fields=[
                ('NomDim', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomPays', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['c_time'],
            },
        ),
        migrations.CreateModel(
            name='Mesures',
            fields=[
                ('NomMes', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Unite', models.CharField(max_length=50, null=True)),
                ('NomDim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.DimentionDeQulite')),
            ],
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('NomFonction', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Formule', models.CharField(max_length=100)),
                ('Valeurs', models.CharField(max_length=50)),
                ('Resultat', models.CharField(max_length=50, null=True)),
                ('Interpretation', models.CharField(max_length=50, null=True)),
                ('NomMes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Mesures')),
            ],
        ),
        migrations.CreateModel(
            name='CSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv', models.FileField(upload_to='csvs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('NomDataset', models.CharField(max_length=50)),
                ('sep', models.CharField(max_length=50)),
                ('CatDataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Categories')),
                ('PaysDataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Pays')),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Annee')),
            ],
            options={
                'unique_together': {('NomDataset', 'uploaded_at')},
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomAttribute', models.CharField(max_length=50)),
                ('Format', models.CharField(max_length=50)),
                ('Statut', models.CharField(max_length=50, null=True)),
                ('reference', models.CharField(max_length=255, null=True)),
                ('NomDataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.CSV')),
            ],
        ),
        migrations.CreateModel(
            name='Analyse_Specific',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resultat', models.CharField(max_length=50)),
                ('NomDataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.CSV')),
                ('NomMes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Mesures')),
            ],
            options={
                'unique_together': {('NomMes', 'NomDataset')},
            },
        ),
        migrations.CreateModel(
            name='Analyse_General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resultat', models.CharField(max_length=50)),
                ('NomDataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.CSV')),
                ('NomMes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Mesures')),
            ],
            options={
                'unique_together': {('NomMes', 'NomDataset')},
            },
        ),
    ]
