# Generated by Django 2.2.5 on 2021-07-01 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DimentionDeQulite',
            new_name='Dimentions',
        ),
    ]
